### ISSUE TITLE
Bug in aldex.clr when using glm model matrix

### ISSUE THREAD

**Issue by orcuttlab** [ggloor/ALDEx2_dev#10]
Greetings - I am trying to use a glm for a 2 factor experimental design and I am getting the error:

Error in coerce.data(reads, conds) : 
  mismatch between number of samples and condition vector

I also get this error when I use the example data provided in the vignette:

selex.sub <- selex[1:400,]
> covariates <- data.frame("A" = sample(0:1, 14, replace = TRUE),
+                          "B" = c(rep(0, 7), rep(1, 7)))
> mm <- model.matrix(~ A + B, covariates)
> x <- aldex.clr(selex.sub, mm, mc.samples=8, denom="all")
Error in coerce.data(reads, conds) : 
  mismatch between number of samples and condition vector

I have thoroughly looked over my data and they have the same amount and samples and the same sample names.

Thank you

**Comment by kevinVervier** [comment]
Same here. I could not run aldex.clr with a model.matrix object.

**Comment by ggloor** [comment]
This has been fixed in the ALDEx_bioc repository. Download and install the version in the dev branch and it should work.
