### ISSUE TITLE
no "conditions" flag option in aldex.effect or aldex.ttest- update directions?

### ISSUE THREAD

**Issue by rrohwer** [ggloor/ALDEx2_dev#11]
Hi, I am trying to use your package for the first time and following directions from this vignette (http://127.0.0.1:15937/library/ALDEx2/doc/ALDEx2_vignette.pdf) which I found via this command: `browseVignettes("ALDEx2")`

I don't see a way to add a `conds = ` argument to supply a conditions vector to either aldex.ttest or to aldex.effect. It looks like this is because the conditions vector is mantained as an element of the clr object after being supplied in aldex.clr.

If I'm interpreting this correctly, then it'd be helpful to update the vignette. For example, the directions for aldex.effect say that " There are four inputs: the aldex object
from aldex.clr, the vector of conditions ..." 

Thanks! I'm looking forward to getting this package working for me :)

**Comment by ggloor** [comment]
The conds argument is now captured directly from the object that is output by the aldex.clr function. you can verify the conds by the following coded

x <- aldex.clr(data, conds)

x@conds
