### ISSUE TITLE
ALDEx2_1.16.0 output of aldex.corr may have a mistake

### ISSUE THREAD

**Issue by daichi-fujii** [ggloor/ALDEx2_dev#12]
Hello

Output of aldex.corr function has column r . However, the contents of the column is "t statistics" of cor.test function, and it should be "r estimate". 

So, code of aldex.corr should be changed as follows.
from
r <- sapply(cors, getElement, "statistic")
to
r <- sapply(cors, getElement, "estimate")

daichi

**Comment by ggloor** [comment]
thank you. will be fixed and pushed to bioconductor
