### ISSUE TITLE
Problem in calculating the differential OTU abundance based on ALDEx2

### ISSUE THREAD

**Issue by tilaknayak** [ggloor/ALDEx2_dev#14]
I am trying to calculating the differential OTU abundance, for this I am trying this code
I attached my file also
[ENV_aldex.txt](https://github.com/ggloor/ALDEx2_dev/files/4021852/ENV_aldex.txt)
[OTU_table_final.txt](https://github.com/ggloor/ALDEx2_dev/files/4021853/OTU_table_final.txt)

" ]
Script:
OTU_FL <- OTU[ , ENV$Water_type == "Radon
OTU_FL <- OTU_FL[ rowSums(OTU_FL) > 0, ]
relOTU_FL <- prop.table(as.matrix(OTU_FL), 2) * 100
ENV_FL <- ENV[ colnames(OTU_FL), ]
OTU_FL.sub <- OTU_FL[apply(OTU_FL, 1, function(x) { max(table(ENV_FL$Type[x > 0])) >=3 } ) &
                       apply(relOTU_FL, 1, function(x) { max(x) >= 1 } ), ]
clrOTU_FL_mc <- aldex.clr(OTU_FL.sub, mc.samples = 128)
clrOTU_FL <- t(sapply(getMonteCarloInstances(clrOTU_FL_mc), function(x) {apply(x, 1, median)}))
glmOTU_FL <- aldex.glm(clrOTU_FL_mc, conditions = ENV_FL$Type)

but I got an error that
**Error in lr2glm(mci_lr, conditions, ...) : 
  Please define the aldex.clr object for a model.matrix 'conditions'.
In addition: Warning message:
In if (class(conditions) != "matrix" & !("assign" %in% names(attributes(conditions)))) { :
  the condition has length > 1 and only the first element will be used**
 Please help me to solve this error.

**Comment by ggloor** [comment]
you need to define a model matrix object. See the example in ?aldex.glm

**Comment by tilaknayak** [comment]
Thanks a lot.

**Comment by mbaloza** [comment]
I have a similar problem 

OTU_table=read.csv("PS118_physeq.csv", h=T)
OTU_St1_St4_2_3=OTU_table[,c(38,44,50,98,104,110)]

OTU_St1_St4_2_3=OTU_St1_St4_2_3[rowSums(OTU_St1_St4_2_3[])>0,]

Conds<-c(rep("St4",3),rep("St1",3))

St1St4_2_3=aldex(OTU_St1_St4_2_3, Conds, mc.samples=128, test="glm",  effect=FALSE, include.sample.summary=FALSE, verbose=FALSE) 

I got this error:

aldex.clr: generating Monte-Carlo instances and clr values
operating in serial mode
computing center with all features
aldex.glm: doing glm test based on a model matrix
Error in lr2glm(mci_lr, conditions, ...) : 
  Please define the aldex.clr object for a model.matrix 'conditions'.

I am using R version 4 and ALDEX2 version 1.20.0
