### ISSUE TITLE
confusion regarding "mc.samples" argument

### ISSUE THREAD

**Issue by mirpie** [ggloor/ALDEx2_dev#18]
Hello!

First off, thanks so much for putting together this incredibly useful package.

I was just hoping to get some clarification regarding the "mc.samples" argument in the initial clr transform function. I think I understand the significance, i.e.  the amount of Monte Carlo instances drawn from a Dirichlet distribution to estimate the underlying technical variation of the sample. However, I'm having difficulty seeing how I can determine the proper amount of sampling for my data and the desired tests. The documentation says that "128 is sufficient for most cases", but that you only need 16 for ANOVA or up to 1000 for rigorous effect sizes. I've also found some literature that achieves good results with only 8 Monte Carlo instances, and shows no differences in results when comparing 8 vs. 128 instances.

With such a range of possibilities I hope you understand my confusion! I want to compare 2 groups, each with size 12, using a KW test. What would be the minimal number of Monte Carlo instances for such a dataset, assuming I want to optimize runtime while achieving accurate results?

Thanks so much!

**Comment by ggloor** [comment]
ALDEx2 uses mixture  distributions. So in general, you want to have enough mc.samples plus samples in each group to give a good distribution. So if you have 2 samples per group, then 1000 mc.samples give 2000 elements in each distribution. If you have 10 samples per group, then 200 mc.samples gives the same 2000 elements in the distribution. However, when you have small sample sizes, you have a lot less information on biological variation and you need to over-compensate with more imputed technical variance. So for your case with 12 samples, then 8-16 mc.samples will likely be enough. In the ideal where you have more samples than features (ha ha) then you would not need and mc.samples, and just use the log-ratio transformed data directly.
