### ISSUE TITLE
could not find function "aldex.plot"

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ggloor/ALDEx2_dev#19]
Hi,

using the latest release, ALDEx2_2.0.6.2, I get this error:

x.all <- aldex(otus, group1, mc.samples=128,test="t",verbose=TRUE)

aldex.plot(x.all, type="MA", test="welch", xlab="Log-ratio abundance",ylab="Difference")

Error in aldex.plot(x.all, type = "MA", test = "welch", xlab = "Log-ratio abundance",  : 
  could not find function "aldex.plot"

Thanks.

**Comment by ggloor** [comment]
please install from bioconductor, or use the version in the ALDEx_bioc repository
