### ISSUE TITLE
Several options are giving errors

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ggloor/ALDEx2_dev#20]
Several options are giving errors:

x.all <- aldex(otus, group1, mc.samples=128,test="t",verbose=TRUE,include.sample.summary=FALSE)

Error in aldex(otus, group1, mc.samples = 128, test = "t", verbose = TRUE,  : 
  unused arguments (test = "t", include.sample.summary = FALSE)

If I use only the command below, it works, but I cannot specify any other options.
x.all <- aldex(otus, group1, mc.samples=128, verbose=TRUE)

**Comment by theo-allnutt-bioinformatics** [comment]
also this

Error in aldex.ttest(x.all, paired.test = FALSE, verbose = TRUE) : 
  could not find function "aldex.ttest"

**Comment by theo-allnutt-bioinformatics** [comment]
There is no explanation of the e.g. ".0.1" - ".99" in the effect statistics in the manual. Can you explain what this means please?

Thanks


effect.95. | effect.99.
-- | --

**Comment by ggloor** [comment]
please install from bioconductor, or use the version in the ALDEx_bioc repository

**Comment by ggloor** [comment]
The effect size is similar to Cohen's d in concept. Effect sizes of > 1 and difference between > 1 are generally large enough to be reproducible

**Comment by theo-allnutt-bioinformatics** [comment]
The bioconductor version is not recent enough to compare >2 groups.

**Comment by ggloor** [comment]
I'm sorry the aldex.glm function in the two repositories is the same. 
Greg

**Comment by theo-allnutt-bioinformatics** [comment]
So the bioconductor version (1.2 I think? Sorry don't have access atm) can use glm for >2 groups and to add multiple covariates to a model?

**Comment by ggloor** [comment]
yes. Let me know if you have problems. 
Greg
