### ISSUE TITLE
Can't use aldex.effect() on aldex.kw() object

### ISSUE THREAD

**Issue by Rob-murphys** [ggloor/ALDEx2_dev#28]
We can't use aldex.effect() on aldex.kw() object so how are we meant to understand the effect and plot it with the package?

```
x = aldex.clr(profile_nitrogen, conds = metadata$Timepoint, mc.samples = 32, denom = "all", verbose = F)

x.kw = aldex.kw(x)

x.effect = aldex.effect(x, CI=T, verbose=FALSE)

>Error in aldex.effect(x, CI = T, verbose = FALSE) : 
  only two condition levels are currently supported
```

**Comment by mirpie** [comment]
Hi,
I believe currently aldex2 only supports two factor levels in your conditions vector, so if you have 3 timepoints it will throw an error. In order to handle a more complex design check out the docs for the aldex2.glm function

**Comment by ggloor** [comment]
you would need to calculate the effect for each condition pair manually if you use the glm function with more than two groups.
