### ISSUE TITLE
Error in data.t[grp1, ] - data.t[grp2, ] : non-conformable arrays

### ISSUE THREAD

**Issue by jorondo1** [ggloor/ALDEx2_dev#34]
Hi,
I'm trying to understand the nature of this error, which is produced after running the `x.tt <- aldex.ttest(clr, paired.test=T, hist.plot=T)` function. It only appears with paired.test=T. 

I'm not sure what info I can provide you with, but the groups (study vs placebo) for which I test the condition are not of equal size. Also, observations are not independent, as we have two saliva samples per participant (at two points in time). 

Does that mean a paired test is impossible to perform?
Thanks in advance!

**Comment by ggloor** [comment]
unfortunately you can't do a paired test if the groups do not have equal sizes

you might try aldex.glm for your case

**Comment by jorondo1** [comment]
Thanks for the advice, that makes sense. Cheers !
