### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lee-s17** [ggloor/ALDEx2_dev#35]
Hi, 
ALDEx2 works well before I upgraded to Ubuntu 22.04, but the following error emerged when I wanted to install it:  

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/[]/4.2/RcppZiggurat/libs/RcppZiggurat.so':
  libgsl.so.23: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted

I am using R 4.2.1 and tried reinstalling Rstudio, but the error persists. Would really appreciate your advice, thanks!

**Comment by ggloor** [comment]
You will need to install Rcpp to make this work. It seems not to be part of the usual RStudio install package or it did not install on your systems

try: install.packages("Rcpp") and install.packages("RcppZiggurat")

 then try installing ALDEx2

**Comment by lee-s17** [comment]
Thank you for your reply! solved the issue by reinstalling rcppziggurat
