### ISSUE TITLE
Paired analysis by variable, not order

### ISSUE THREAD

**Issue by mariamaseng** [ggloor/ALDEx2_dev#37]
Hello,
thanks for making this great package. I have a paired dataset where I would like to apply aldex2 paired test. However, I do not have my data organized by order, but rather a column to identify which samples are paired (host_id). Is there a way around this, instead of transforming the data into wide format?

Thanks!

**Comment by ggloor** [comment]
Hi: at this point ALDEx2 requires the data to be in wide format
