### ISSUE TITLE
Confidence interval

### ISSUE THREAD

**Issue by SinaedaA** [ggloor/ALDEx2_dev#38]
Hi ! 
Maybe it's me misunderstanding the confidence interval feature, but I feel like the explanation given in Bioconductor is really unclear.
When I run `aldex.effect(x, CI=TRUE)`, I get two more rows, "effect.high" and "effect.low", both of which are just never explained in the manual. In that same manual, you show the plots where features with a CI > 95% are circled in blue, but never show what data you use to circle these features. 
What is effect.high and effect.low? How do they relate to the confidence interval? 
Also, just to be sure, is the q-value the corrected p-value ? 
I would really like to use this package, but I strongly feel the manual could contain better explanations and more representative examples (as well as including the code used to generate all graphs).
Thank you for your help !

**Comment by ggloor** [comment]
yes, the CI is the 95% CI of the effect size. you can visualize the effect size distribution with the aldex.plotFeature() function to get a sense of the underlying posterior
The q value is the expected Benjamini-Hochberg corrected p-value
