### ISSUE TITLE
Unexpected effect directions

### ISSUE THREAD

**Issue by ijhoskins** [ggloor/ALDEx2_dev#39]
This issue is similar to https://github.com/ggloor/ALDEx2_dev/issues/21

However it doesn't seem like this feature has been implemented yet. Currently, coercion of the conditions character vector to factor causes the levels to be in alphabetical order, which may produce effect sizes in the unexpected direction.

One possible solution is for the conditions argument to accept a factor so that the user can re-level and have control of the which group is the reference.

**Comment by ggloor** [comment]
Thank you for the suggestion. Its been on my to-do list for a while
