### ISSUE TITLE
Feature request: confidence interval parameter for aldex()

### ISSUE THREAD

**Issue by ijhoskins** [ggloor/ALDEx2_dev#41]
Hello @ggloor 

I would like to use aldex() to get both p-values and CIs. However when I pass CI=TRUE to aldex() no CIs are output.

It seems the only way to do this is to call aldex.clr() then aldex.effect() and aldex.ttest() and combine the results.

**Comment by ggloor** [comment]
at the moment, you are correct, you must do this manually
I've added the appropriate code and parameter to aldex() and this will be in the next release
