### ISSUE TITLE
ALDEx2 for multiple (3) groups

### ISSUE THREAD

**Issue by jspychalla** [ggloor/ALDEx2_dev#42]
Hi, 

   I am new to using ALDEx2. I looked at the tutorial. I was wondering can I perform an ALDEx2 analysis on three groups? Or is this tool just designed to look at two groups at a time ? 

Thank you :)

**Comment by ggloor** [comment]
No problem there at all. Check out the aldex.glm option. It is slower, but is exactly what you want for this
