### ISSUE TITLE
Feature Request - comparisons between multiple groups

### ISSUE THREAD

**Issue by stro0070** [ggloor/ALDEx2_dev#6]
Hi,

Can ALDEx2 be expanded to do post-hoc testing and report results of comparisons between multiple groups, like it does between two groups?  For example, my project has 16 different treatments, and I would like to be able to see whether features (OTUs) are significantly more abundant in certain treatments over others, identified by a Tukey's HSD significance category letter or something similar.  It would also be great to be able to extract mean CLRs from each treatment as well as CLRs associated with features (OTUs) from individual samples.  

Thanks,
Noah Strom

**Comment by ggloor** [comment]
Noah
Could you open the request on ALDEx_bioc? As a partial answer:

you can get the expected clr value for each feature by setting the parameter: include.sample.summary = FALSE
using aldex.effect()

The expected clr for each treatment is the rab.win.group column in the output from that same function.

I will try an implement something similar to Tukey's HSD in the future
