### ISSUE TITLE
feature request - controlling for additional variables

### ISSUE THREAD

**Issue by mstagliamonte** [ggloor/ALDEx2_dev#7]
Hi,

Thank you for Aldex2, I have just started using it and love it; I also love the clear manual and vignette.

I was wondering if there are any plans  to account for multiple variables when using a dependent variable ("conditions"), e.g. I might want to control for gender of subjects, day of DNA  extraction, or day of sequencing.

Thank you for your kind attention,
Max

**Comment by ggloor** [comment]
Max

Could you open this in the ALDEx_bioc repository instead. Thanks
We have this instantiated in the development version at bioconductor.

**Comment by mstagliamonte** [comment]
Thank you, GGloor,

I have just submitted a question the the Bioconductor forum. I'm looking forward to the new version!

Best,
Max
